services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD

  backend:
    depends_on:
      - db
    env_file:
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://$PG_USER:$PG_PASSWORD@db/$PG_DB
      BACKEND_PORT_INTERNAL: $BACKEND_PORT_INTERNAL
      GROQ_API_KEY: $GROQ_API_KEY
    ports:
      - "4000:$BACKEND_PORT_INTERNAL"
    volumes:
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules

  frontend:
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      NODE_ENV: development
      BACKEND_URL: $BACKEND_URL
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      # - ./frontend/node_modules
      # - ./frontend/.next

# Uncomment this section if you want to use pgAdmin
  # pgadmin_web:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "8898:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
  #     PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
  #   volumes:
      # - pga-data:/var/lib/pgadmin # Don't forget to uncomment the volume section below

  dbeaver:
    image: dbeaver/cloudbeaver
    ports:
      - "8899:8978"
    volumes:
      - dbeaver-data:/opt/cloudbeaver/data

volumes:
  pg-dev-data:
  dbeaver-data:
  # pga-data:
  