version: "3.8"
services:
  db:
    image: postgres:16
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD

  backend:
    depends_on:
      - db
    env_file:
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://$PG_USER:$PG_PASSWORD@db/$PG_DB
      BACKEND_PORT_INTERNAL: $BACKEND_PORT_INTERNAL
    ports:
      - "4000:$BACKEND_PORT_INTERNAL"
    volumes:
      - ./backend:/backend
      # - ./backend/node_modules

  frontend:
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      NODE_ENV: development
      BACKEND_URL: $BACKEND_URL
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      # - ./frontend/node_modules
      # - ./frontend/.next

volumes:
  pg-dev-data:
  