# docker compose -f docker-compose-be-no-db.yml up
services:
  backend:
    env_file:
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
      DATABASE_URL: $DATABASE_URL
      BACKEND_PORT_INTERNAL: $BACKEND_PORT_INTERNAL
      GROQ_API_KEY: $GROQ_API_KEY
    ports:
      - "4000:$BACKEND_PORT_INTERNAL"
    volumes:
      - ./backend:/backend
    restart: always
