FROM node:lts-alpine

RUN npm install -g pnpm

WORKDIR /backend

# Copy package.json and pnpm-lock.yaml first
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy the rest of the source code
COPY . .

# Generate Prisma client code
RUN pnpm db:generate

# Build the app
RUN pnpm build

CMD pnpm start
EXPOSE 4000