name: Auto Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} 'cd ~/apps/alt-form && git pull && docker compose -f docker-compose-be-no-db.yml down && docker compose -f docker-compose-be-no-db.yml up -d'

      # Only run this step if the deployment is successful
      - name: Notify Success
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed."

      # Only run this step if the deployment fails
      - name: Notify Failure
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has failed to deploy."
